#!/usr/bin/env bash
# configure HAproxy to web-01 and web-02
# distribute load using roundrobin algorithm
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install haproxy=2.4.\*
sed -i "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalace roundrobin\n\tmode http\n\tserver 1484-web-01 34.139.86.96:80 check\n\tserver 1484-web-02 34.204.187.38:80 check\n" /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
