#!/usr/bin/env bash
# loops from 1 to 10 and display "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Best School" for the other iterations
x=1
y=4
z=8
while [ $x -le 10 ]
do
    if [[ "$x" == "$y" ]]
    then
	echo "bad luck"
    elif [[ "$x" == "$z" ]]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    x=$(( x + 1 ))
done
