#!/usr/bin/env bash
# Runing Nginx as nginx user and nginx mustlistening on all active IPs on port 8080
pkill apache2
sed -i 's/^user.*/user nginx;/' /etc/nginx/nginx.conf
sudo -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
