#!/usr/bin/env bash
# Runing Nginx as nginx user and nginx mustlistening on all active IPs on port 8080
sudo pkill -1 apache2
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
